add Jup + update CLI to update mapping only for spot/twap
hubbleprotocol/scope pull request #249
Opened 2024-01-29 21:19 UTC by silviutroscot

2024-01-29 21:36 UTC, oeble requested changes

2024-01-29 21:36 UTC, oeble commented on off_chain/scope-cli/src/main.rs
> +        mode: PriceMode,
I don't really like "mode"; it is not explicit IMO.

2024-01-29 21:36 UTC, oeble commented on Makefile
> +  fi
You should not pass `--mode` if the variable to pass has the same name as this parameter have the `env` attribute anyway. By doing it like this, we can't call `make update-mapping` anymore without setting the env variable...

2024-01-29 21:36 UTC, oeble commented on off_chain/scope-cli/src/scope_client.rs
> +            let local_entry = self.tokens.get(&token_idx).unwrap();
Could you rewrite with the old iterator style but add a filter instead?

2024-01-29 21:36 UTC, oeble commented on off_chain/scope-cli/src/scope_client.rs
> +                .filter(|(_, entry)| !entry.get_label().contains("TWAP"))
This is an unreliable heuristic IMO. You should rather filter on the price type being `ScopeTwap`

2024-01-29 21:36 UTC, oeble commented on off_chain/scope-cli/src/utils.rs
> +}
Please derive the [`clap::ValueEnum`](https://docs.rs/clap/latest/clap/trait.ValueEnum.html) instead. Also, add doc comments to each enum variant so the inline help is generated correctly for clap.

2024-01-29 21:48 UTC, silviutroscot commented on Makefile
> +      RUST_BACKTRACE=1 RUST_LOG="scope_client=trace,scope=trace" cargo run -p scope-cli -- --cluster $(URL) --keypair $(OWNER_KEYPAIR) --program-id $(SCOPE_PROGRAM_ID) --price-feed $(FEED_NAME) uploa
removed as we can pass it to the generic `update-mapping`

2024-02-01 20:40 UTC, oeble approved these changes

2024-02-01 20:45 UTC, merged