Add switchboard v1/v2 support in Scope
hubbleprotocol/scope pull request #27
Opened 2022-04-06 05:42 UTC by gmmour1

2022-04-07 10:22 UTC, y2kappa reviewed
good stuff, seem like it still needs a bit of clean up

2022-04-07 10:22 UTC, y2kappa commented on programs/pyth/src/lib.rs
> +    pub fn set_price_switchboard_v1(ctx: Context<SetPrice>, mantissa: i128, scale: u32) -> ProgramResult {
is there also a set_price_v2?

2022-04-07 10:22 UTC, y2kappa commented on programs/scope/src/utils/yitoken.rs
> +        PriceType::SwitchboardV1 => return Err(ScopeError::BadTokenType.into()),
why would you call get_price on something that is not YiToken, this should be handled upstream, price-type should not be an input into this function, seems redundant

2022-04-07 10:22 UTC, y2kappa commented on tests/pyth_utils.ts
> +export const createPriceFeedSwitchboardV1 = async ({
use formatting like in hubble ts tests please

2022-04-07 12:00 UTC, gmmour1 commented on programs/pyth/src/lib.rs
> +    pub fn set_price_switchboard_v1(ctx: Context<SetPrice>, mantissa: i128, scale: u32) -> ProgramResult {
yes, I've moved those functions back in and implemented the tests.

2022-04-07 12:19 UTC, gmmour1 commented on programs/scope/src/utils/yitoken.rs
> +        PriceType::SwitchboardV1 => return Err(ScopeError::BadTokenType.into()),
I refactored this, moved the check in the handler rather than in the helper function.

2022-04-07 12:35 UTC, gmmour1 commented on tests/pyth_utils.ts
> +export const createPriceFeedSwitchboardV1 = async ({
ran the formatter on all the TS tests, can you check?

2022-04-08 10:45 UTC, elliotkennedy commented on programs/scope/src/handlers/handler_refresh_prices.rs
>      let pyth_price_info = &ctx.accounts.pyth_price_info;
Let's rename this to `price_mapping` or `price_info` or something not Pyth related

2022-04-08 10:48 UTC, elliotkennedy commented on programs/scope/src/handlers/handler_refresh_prices.rs
>      let pyth_price_info = &ctx.accounts.pyth_price_info;
And fix the comment below

2022-04-08 10:54 UTC, elliotkennedy commented on programs/scope/src/handlers/handler_yitoken_prices.rs
> +    match price_type {
Can you add a test for this? I don't think it will work as expected

2022-04-08 10:57 UTC, elliotkennedy commented on programs/scope/src/handlers/handler_update_mapping.rs
> +    if price_type == PriceType::Pyth as u8 {
rename `UpdateOracleMapping.pyth_price_info` to be non-pyth specific

2022-04-08 11:02 UTC, elliotkennedy reviewed
Please run `cargo clippy --fix` to fix the rust formatting 

Also add a liniting workflow step - like in hubble - https://github.com/hubbleprotocol/hubble/blob/master/.github/workflows/rust.yml#L173

2022-04-08 11:04 UTC, elliotkennedy commented on programs/scope/src/utils/switchboard_v2.rs
> +//use core::num::dec2flt::float::RawFloat;
Remove this in both switchboard files if not needed

2022-04-08 11:09 UTC, elliotkennedy commented on programs/scope/src/utils/switchboard_v1.rs
> +    // if aggregator.version.unwrap() != 1 {
There are a few commented out lines here - what is the plan for validation? Version check seems reasonable - with tests ofc!

2022-04-08 11:11 UTC, elliotkennedy commented on programs/scope/src/lib.rs
> +extern crate core;
Is this used? I think `extern` syntax is no longer needed - https://stackoverflow.com/questions/64623568/why-sometimes-extern-crate-is-needed

2022-04-08 11:13 UTC, elliotkennedy commented on programs/scope/src/lib.rs
> +    SwitchboardV2Error,
I think `PriceNotValid` should nearly always suffice here

2022-04-08 11:14 UTC, elliotkennedy commented on tests/test_switchboard.ts
> +    // let fakePythAccounts2: Array<PublicKey>; // Used to overflow oracle capacity
Remove if not needed

2022-04-08 11:16 UTC, elliotkennedy commented on tests/test_crank.ts
> +    // {
Can this be uncommented?

2022-04-08 11:20 UTC, elliotkennedy requested changes
Looking good! Just a few comments around testing and a bit of polish :+1:

2022-04-08 11:34 UTC, gmmour1 commented on tests/pyth_utils.ts
> +export const createPriceFeedSwitchboardV1 = async ({
Done and ran prettier, committed as a separate commit

2022-04-08 11:41 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v1.rs
> +    // if aggregator.version.unwrap() != 1 {
Done. This function won't work with the wrong version. the validation was copied (as it is commented out) from Solend but it is useless as the aggregator does not contain version anymore (field is deprecated). v1 and v2 formats are different and functions won't work with each other.

2022-04-08 11:41 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v2.rs
> +//use core::num::dec2flt::float::RawFloat;
Done

2022-04-08 11:45 UTC, gmmour1 commented on programs/scope/src/lib.rs
> +extern crate core;
Removed it and build fine indeed. @oeble @y2kappa  any objections? This was probably there since one of you two wrote it.

2022-04-08 11:47 UTC, gmmour1 commented on programs/scope/src/lib.rs
> +    SwitchboardV2Error,
I created this error for when the switchboard_v2::aggregator::get_result() method returns an error. Because it's an external error rather than internal. Happy to remove it as well.

2022-04-08 11:48 UTC, gmmour1 commented on tests/test_switchboard.ts
> +    // let fakePythAccounts2: Array<PublicKey>; // Used to overflow oracle capacity
Done.

2022-04-08 11:48 UTC, gmmour1 commented on tests/test_crank.ts
> +    // {
I've completely refactored the crank tests just now, please re-check

2022-04-08 12:11 UTC, gmmour1 commented on programs/scope/src/handlers/handler_update_mapping.rs
> +    if price_type == PriceType::Pyth as u8 {
done

2022-04-08 12:11 UTC, gmmour1 commented on programs/scope/src/handlers/handler_refresh_prices.rs
>      let pyth_price_info = &ctx.accounts.pyth_price_info;
done

2022-04-08 12:32 UTC, elliotkennedy commented on tests/pyth_utils.ts
> +export const createPriceFeedSwitchboardV1 = async ({
Ok thanks - 2 things on this - 

1) hubble only runs prettier against TS files - this commit is great but in the future we should restrict to just TS. The best way to do this is in the `package.json` file - https://github.com/hubbleprotocol/hubble/pull/493/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R12

Hubble also does this in the makefile but it requires a global prettier installation so we should use the method above. You can run it with `yarn prettier`

2) Could you also add this workflow - https://github.com/hubbleprotocol/hubble/blob/master/.github/workflows/prettier.yml - to fail the build if prettier has not been run please?

2022-04-08 12:53 UTC, elliotkennedy commented on programs/scope/src/lib.rs
> +extern crate core;
Not to worry but this is not in master!

2022-04-08 12:56 UTC, elliotkennedy commented
> Please run `cargo clippy --fix` to fix the rust formatting
> 
> Also add a liniting workflow step - like in hubble - https://github.com/hubbleprotocol/hubble/blob/master/.github/workflows/rust.yml#L173
> 
> GM reply: (can't reply as a comment) this is done

Don't forget the workflow step!

2022-04-08 13:02 UTC, gmmour1 commented on programs/scope/src/handlers/handler_yitoken_prices.rs
> +    match price_type {
Yep, added tests and works as expected

2022-04-08 13:12 UTC, gmmour1 commented on tests/pyth_utils.ts
> +export const createPriceFeedSwitchboardV1 = async ({
Done both 1 and 2

2022-04-08 13:24 UTC, gmmour1 commented
> > Please run `cargo clippy --fix` to fix the rust formatting
> > Also add a liniting workflow step - like in hubble - https://github.com/hubbleprotocol/hubble/blob/master/.github/workflows/rust.yml#L173
> > GM reply: (can't reply as a comment) this is done
> 
> Don't forget the workflow step!

Done the workflows

2022-04-08 18:23 UTC, elliotkennedy commented on programs/scope/src/lib.rs
> +    SwitchboardV2Error,
Ok cool - thanks for explaining - sounds good to me

2022-04-09 10:18 UTC, oeble requested changes
Sorry for the late review. Good job reverse-engineering the switchboard serialization.

2022-04-09 10:18 UTC, oeble commented on .github/workflows/ts-integration.yaml
>              'cargo test',
don't we discussed of adding `cargo clippy` and `cargo fmt --check` here?

2022-04-09 10:18 UTC, oeble commented on tests/mock_account_utils.ts
> +export const createPriceFeed = async ({ oracleProgram, initPrice, confidence, expo = -8 }: ICreatePriceFeed) => {
Can you make explicit by the name what is pyth specific?

2022-04-09 10:18 UTC, oeble commented on tests/test_crank.ts
> +    expo: 1,
Having this for all prices seems a bit unpractical...Why don't we compute this from the Decimal price anyway?

2022-04-09 10:18 UTC, oeble commented on tests/test_yi_token.ts
> +  },
I think you already answered to the same comments on previous PR but since you duplicate the same const on each test file, why don't you put it in a common file or similar?

2022-04-11 05:35 UTC, gmmour1 commented on deps/usdhusd.json
> +  "pubkey": "37NFcKPTgqUVx3gwTQ4c2Q94oJWk2xZy3NQUXtDixReb",
I've removed these, they were leftover from the first phase where I was testing the new switchboard accounts using account dumps

2022-04-11 06:12 UTC, gmmour1 commented on programs/pyth/Cargo.toml
> +switchboard-program = "=0.2.0"
renamed path to mock_oracles and refactored the ts tests

2022-04-11 06:20 UTC, gmmour1 commented on programs/pyth/src/lib.rs
> +    pub fn set_price_switchboard_v1(
actually set_price and set_trading etc should be called set_price_pyth and set_trading_pyth as they are pyth specific rather than generic. I think we should rename them with _pyth to be explicit, what do you think? @oeble

2022-04-11 06:29 UTC, gmmour1 commented on programs/pyth/src/lib.rs
> +        let _ = account_data[..8].copy_from_slice(&discriminator);
committed

2022-04-11 06:29 UTC, gmmour1 commented on programs/pyth/src/lib.rs
> +        let discriminator: [u8; 8] = [217, 230, 65, 101, 201, 162, 27, 125];
committed

2022-04-11 06:29 UTC, gmmour1 commented on programs/pyth/src/lib.rs
> +        //let _ = switchboard_program::get_aggregator(&ctx.accounts.price).unwrap();
ack

2022-04-11 07:15 UTC, oeble commented on programs/pyth/src/lib.rs
> +    pub fn set_price_switchboard_v1(
Yes, that's my point, generic names but not behavior.

I think splitting the file into multiple ones is overall better but I'm fine with just a rename since the size of the file is still pretty small.

2022-04-11 08:55 UTC, gmmour1 commented on deps/usdhusd.json
> +  "pubkey": "37NFcKPTgqUVx3gwTQ4c2Q94oJWk2xZy3NQUXtDixReb",
also moved the deps folder under tests/deps/ there's only one account dump now that we're using for yi token (solustscope.json)

2022-04-11 08:59 UTC, gmmour1 commented on programs/scope/src/handlers/handler_update_mapping.rs
> +    let _price_type: PriceType = price_type
Thanks! This is good Rust practice indeed, I've refactored the file!

2022-04-11 09:04 UTC, gmmour1 commented on programs/scope/src/handlers/handler_update_mapping.rs
> +    }
good point, I'm developing the sanity checks now as discussed.

2022-04-11 11:52 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v2.rs
> +    let exp: u64 = price_switchboard_desc.scale as u64;
fixed

2022-04-11 11:53 UTC, gmmour1 commented on programs/scope/src/handlers/handler_yitoken_prices.rs
> +        PriceType::SwitchboardV2 => return Err(ScopeError::BadTokenType.into()),
commited

2022-04-11 12:50 UTC, gmmour1 commented on programs/scope/src/utils/mod.rs
> +    SwitchboardV2,
Done

2022-04-11 12:52 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v1.rs
> +    //let (mantissa, exponent, sign) = price_float.integer_decode();
ack

2022-04-11 15:14 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v1.rs
> +    let price: u64 = (price_quotient * price_float) as u64;
done as we agreed

2022-04-11 15:20 UTC, gmmour1 commented on .github/workflows/ts-integration.yaml
>              'cargo test',
I added it inside the workflow file but it ended up timing out. We need to find another way to do this.

2022-04-11 15:25 UTC, gmmour1 commented on tests/mock_account_utils.ts
> +export const createPriceFeed = async ({ oracleProgram, initPrice, confidence, expo = -8 }: ICreatePriceFeed) => {
done

2022-04-11 15:27 UTC, gmmour1 commented on tests/test_yi_token.ts
> +  },
yeah, tried to do this, but my main issue was that there are small differences in the list of tokens we are passing, so I thought it makes more sense to leave them separate for each test. for example in yitoken test I did not update the test itself for switchboard. but yeah, it is a good point. also one other thing is that in some tests I change the value and I save it back into the variable to then use the generic verification function. this can cause problems if it is a const or if it is a mutable variable and we are re-using it and updating it...

2022-04-11 15:41 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v1.rs
> +    let exp = 8u32;
moved these at the top

2022-04-11 15:42 UTC, gmmour1 commented on programs/scope/src/handlers/handler_yitoken_prices.rs
> +        PriceType::SwitchboardV2 => return Err(ScopeError::BadTokenType.into()),
done

2022-04-11 15:48 UTC, gmmour1 commented on programs/scope/src/utils/mod.rs
> +        PriceType::SwitchboardV2 => switchboard_v2::get_price(price_acc),
re-ordered, the other cases use specific functions so I just put the error case last

2022-04-11 15:50 UTC, gmmour1 commented on tests/test_crank.ts
> +    expo: 1,
It's the other way around. For switchboard v2, we want to test different expo lengths, we could calculate the decimal price from mantissa and expo. I believe that it's better to keep the fields seaparate. v1 requires a decimal price and v2 requires mantissa and expo. it's just easier to fit the two together in one struct. what do you think?

2022-04-13 05:22 UTC, oeble commented on programs/scope/src/handlers/handler_update_mapping.rs
> +    let _price_type: PriceType = price_type
Ok with the changes but you did not shadow the variable. You named it `price_type` which makes it still usable later.

2022-04-13 05:27 UTC, gmmour1 commented on programs/scope/src/handlers/handler_update_mapping.rs
> +    let _price_type: PriceType = price_type
I kept the original variable as u8 and named the new PriceType enum variable differently because we need to use both types further down as enum to check and as u8 to save it in the oracle_mappings.
In any case if it fails to convert we will throw a BadTokenType error and we won't proceed to the update.

2022-04-13 05:58 UTC, oeble commented on programs/scope/src/utils/pyth.rs
> +//!    the oracle mapping. However some information present only in the associated mock_oracles product account are
Changes to this file are a mistake I think.

2022-04-13 05:58 UTC, oeble commented on programs/scope/src/utils/switchboard_v1.rs
> +    let price: u64 = (price_float * PRICE_MULTIPLIER) as u64;
This way of doing it is a proposal I made but I would like more opinions @elliotkennedy @y2kappa

2022-04-13 05:58 UTC, oeble commented on programs/scope/src/utils/switchboard_v2.rs
> +    }
As discussed yesterday, this is probably not enough.

2022-04-13 06:05 UTC, oeble commented on programs/scope/src/handlers/handler_update_mapping.rs
> +    let _price_type: PriceType = price_type
For this one it's ok but in the general case, I don't think we should consider this a reciprocal operation. Multiple parameters can match one enum variant. But then we want one variant to match only one value in its integer representation because we use it as an index in arrays internally. Security-wise, shadowing is important when transforming the data because it prevents further usage that does not implement the security checks. Also, `enum_variant.into()` is usually a no-op once compiled.

2022-04-13 18:00 UTC, gmmour1 commented on programs/scope/src/utils/pyth.rs
> +//!    the oracle mapping. However some information present only in the associated mock_oracles product account are
done

2022-04-13 18:50 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v1.rs
> +    let price: u64 = (price_float * PRICE_MULTIPLIER) as u64;
yes, this is an interesting one. the question for @elliotkennedy @y2kappa understanding is:
How do we make sure that the f64 we get from Switchboard v1 fits in a u64 (we can only cast by using 'as u64' in this case).
The current solution we discussed with @oeble and I implemented is that we choose an arbitrarily huge number (10 billion in our case) and we reject prices that are larger than that.

2022-04-13 21:54 UTC, oeble commented on programs/scope/src/utils/switchboard_v1.rs
> +    };
Are you sure "min_confirmations" is the number of possible contributors? Feels like an already checked minimum by switchboard...

2022-04-13 21:54 UTC, oeble commented on programs/scope/src/utils/switchboard_v1.rs
> +    Ok(dated_price)
So no confidence interval check on v1?

2022-04-13 21:54 UTC, oeble commented on programs/scope/src/utils/switchboard_v2.rs
> +    };
I think is better to avoid division if possible. Get the simplest computation here only:
1. Compute Price and stdev as a Scope price (value + expo) with the same number of decimals for both
2. Check that stdev.value * 50 < price.value

Also, I think `u128` is unnecessary here.

2022-04-13 21:54 UTC, oeble commented on programs/scope/src/utils/tests_utils.rs
> +    use spl_token::solana_program::hash::Hash;
I think those tests would be very fine living in the same file as the function they test: https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests

2022-04-13 21:54 UTC, oeble commented on programs/scope/src/utils/switchboard_v2.rs
> +
```suggestion
const MIN_CONFIDENCE_PERCENTAGE: u64 = 2u64;
const CONFIDENCE_FACTOR:u64 = 100/MIN_CONFIDENCE_PERCENTAGE;
```

2022-04-13 21:55 UTC, oeble commented on tests/test_yi_token.ts
> +  },
It will be reworked in my next PR

2022-04-13 21:55 UTC, oeble commented on tests/test_crank.ts
> +    expo: 1,
will be reworked in my next PR.

2022-04-14 05:42 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v1.rs
> +    };
I checked their website, they are only supposed to have two fields on each v1 oracle 'minimum update delay seconds' and 'minimum oracle results'. from looking at the Configs struct it only has two Option integer fields min_confirmations and min_update_delay_seconds, therefore I concluded that min_confirmations is the number of possible contributors that they show on their website as minimum oracle results. 

They do the check themselves only in v2 not in v1. In v1 you just have an Option<f64> result. In v2 you have a get_result method that does a hard check versus their inbuilt minimum, so in that case we could argue that our check is redundant

2022-04-14 05:43 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v1.rs
> +    Ok(dated_price)
v1 does not provide a stdev, they give us a Sec<f64> of medians, we could use that to calculate our own metrics. Do you think this is a good idea?

2022-04-14 05:44 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v2.rs
> +    };
Yes I thought about that, but I thought it would make the code less easy to understand, but I completely agree, so I'll implement it now!

I prefer u128 because we basically upscaling some numbers. It could be redundant but what is the drawback?

2022-04-14 05:54 UTC, gmmour1 commented on programs/scope/src/utils/tests_utils.rs
> +    use spl_token::solana_program::hash::Hash;
Done

2022-04-14 05:58 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v2.rs
> +
Ah, just saw this after I pushed the change above, I've refactored to match what you suggested, but I used u128. What is the benefit/drawback of using a larger number to fit the multiplication of u64, is it an overkill?

2022-04-14 06:09 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v2.rs
> +
Actually, trying to refactor this to use u64 is blowing up one of my unit tests where I used a scale of 30!

I have seen a scale (precision) of 15, so 30 is not that far away, so I suggest we stick with u128 if you don't ming.
It's test test_valid_switchboard_v2_price_stdev_zero where I have stdev_mantissa 0 and stdev_scale 30...

2022-04-14 06:10 UTC, gmmour1 commented on programs/scope/src/utils/switchboard_v2.rs
> +
It's blowing up when I'm doing 10u64.checked_pow(30)

2022-04-14 07:43 UTC, oeble commented on programs/scope/src/utils/switchboard_v1.rs
> +    };
What I had in mind was from this page https://docs.switchboard.xyz/api/idl/accounts/AggregatorAccountData

Field | Type | Description
-- | -- | --
oracleRequestBatchSize | u32 | Number of oracles assigned to an update request
minOracleResults | u32 | Minimum number of oracle responses required before a round is validated.
minJobResults | u32 | Minimum number of job results before an oracle accepts a result

So my proposal was to use `oracleRequestBatchSize` to up the `minOracleResults` to 3 if it is below this...

But I don't find those in the deserialized struct they give back from their API...I'm a bit lost here, what are we using. Also, it's unclear if this is V1 or V2 (looks like v2 because...anchor IDL)

2022-04-14 07:44 UTC, oeble commented on programs/scope/src/utils/switchboard_v1.rs
> +    Ok(dated_price)
It's not as good but we could use (max-min) like stdev (with 3 value is basically the same IMO).

2022-04-14 07:53 UTC, oeble commented on programs/scope/src/utils/switchboard_v2.rs
> +    };
Just write a comment explaining the value, it will be more readable anyway than all those checked operations.

Also, I usually prefer to stick to what is needed instead of blindly using bigger variables. `u128` is twice the size of `u64` and probably 4 times the [compute](https://godbolt.org/z/TjPhbqea7) units. Not very significant here but might be in the larger picture of updating multiple prices at once.

2022-04-14 07:56 UTC, oeble commented on programs/scope/src/utils/switchboard_v2.rs
> +
Why do you need the scale? If the base value of stdev*confidence ratio doesn't fit `u64` then the price itself won't fit either since this computation result shall be smaller than the price one...We store the price in `u64` in the end...

2022-04-15 06:39 UTC, gmmour1 commented
approved by @y2kappa for merge, please review post merge

2022-04-15 07:02 UTC, merged